version: "3.6"
services:
  redis-cache:
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    logging:
      options:
        max-size: "10m"
        max-file: "3"
